services:
  - type: web
    name: movie-ticket-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    envVars:
      - key: DB_URI
        value: "mongodb+srv://arun_db:%40Madhumitha143@arundb.wufug.mongodb.net/ticket_booking_app?retryWrites=true&w=majority&appName=ArunDB"
      - key: PORT
        value: "5000"
