services:
  - type: web
    name: movie-ticket-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    envVars:
      - key: DB_HOST
<<<<<<< HEAD
        value: 127.0.0.1
=======
        value: "movie-ticket-booking-app-1.mysql.render.com"  # Correct host
>>>>>>> e805fee31f9ce79fd4fe31e701e833350b261910
      - key: DB_USER
        value: "root"
      - key: DB_PASSWORD
        value: "%40madhumitha143"  # URL encoded password
      - key: DB_NAME
        value: "ticket_booking"
