services:
  - type: web
    name: movie-ticket-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    envVars:
      - key: DB_HOST
        value: "movie-ticket-booking-app-1.mysql.render.com"  # Correct host
      - key: DB_USER
        value: "root"
      - key: DB_PASSWORD
        value: "%40madhumitha143"  # URL encoded password
      - key: DB_NAME
        value: "ticket_booking"
