services:
  - type: web
    name: movie-ticket-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    envVars:
      - key: DB_HOST
        value: "127.0.0.1"
      - key: DB_USER
        value: "root"
      - key: DB_PASSWORD
        value: "@madhumitha143"  # URL encoded password (@ becomes %40)
      - key: DB_NAME
        value: "ticket_booking"
      - key: DB_PORT
        value: "3306"
